// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.service-account@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SERVICE_ACCOUNT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SERVICE_ACCOUNT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_service_account { () => { "{\"capability_id\":\"lenso.service-account@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"create\",\"get\",\"list\",\"revoke\",\"rotate_secret\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_service_account_client { () => { "{\"capability_id\":\"lenso.service-account@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_service_account_client { () => { "{\"capability_id\":\"lenso.service-account@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CREATE_OPERATION: &str = "create";
pub const GET_OPERATION: &str = "get";
pub const LIST_OPERATION: &str = "list";
pub const REVOKE_OPERATION: &str = "revoke";
pub const ROTATE_SECRET_OPERATION: &str = "rotate_secret";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateServiceAccountRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateServiceAccountResponse {
    #[serde(rename = "account")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub account: ServiceAccountSummary,
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "secret")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub secret: Option<String>,
}

impl fmt::Debug for CreateServiceAccountResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateServiceAccountResponse")
            .field("account", &self.account)
            .field("created", &self.created)
            .field("secret", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ServiceAccountSummary {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "credential_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential_expires_at: Option<Timestamp>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "rotated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub rotated_at: Option<Timestamp>,
    #[serde(rename = "service_account_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_account_id: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ServiceAccountStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ServiceAccountStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "revoked")]
    Revoked,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateError {
    AccessDenied,
    DirectoryRejected,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    MembershipRequired,
    NameConflict,
    OperationInProgress,
    OrganizationNotFound,
    TooManyServiceAccounts,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetServiceAccountRequest {
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "service_account_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_account_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetServiceAccountResponse {
    #[serde(rename = "account")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub account: ServiceAccountSummary,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetError {
    AccessDenied,
    Forbidden,
    InvalidRequest,
    MembershipRequired,
    NotFound,
    OrganizationNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListServiceAccountsRequest {
    #[serde(rename = "after")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub after: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListServiceAccountsResponse {
    #[serde(rename = "accounts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accounts: Vec<ServiceAccountSummary>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListError {
    AccessDenied,
    Forbidden,
    InvalidRequest,
    MembershipRequired,
    OrganizationNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeServiceAccountRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "service_account_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_account_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeServiceAccountResponse {
    #[serde(rename = "account")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub account: ServiceAccountSummary,
    #[serde(rename = "revoked")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeError {
    AccessDenied,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    MembershipRequired,
    NotFound,
    OperationInProgress,
    OrganizationNotFound,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RotateServiceAccountSecretRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "service_account_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_account_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RotateServiceAccountSecretResponse {
    #[serde(rename = "account")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub account: ServiceAccountSummary,
    #[serde(rename = "rotated")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub rotated: bool,
    #[serde(rename = "secret")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub secret: Option<String>,
}

impl fmt::Debug for RotateServiceAccountSecretResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RotateServiceAccountSecretResponse")
            .field("account", &self.account)
            .field("rotated", &self.rotated)
            .field("secret", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum RotateSecretError {
    AccessDenied,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    MembershipRequired,
    NotFound,
    OperationInProgress,
    OrganizationNotFound,
    RevisionConflict,
    Revoked,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ServiceAccountCreate;
impl RequestCapability for ServiceAccountCreate {
    type Request = CreateServiceAccountRequest;
    type Response = CreateServiceAccountResponse;
    type DomainError = CreateError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ServiceAccountRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create(context, request)
    }
}

#[derive(Debug)]
pub struct ServiceAccountGet;
impl RequestCapability for ServiceAccountGet {
    type Request = GetServiceAccountRequest;
    type Response = GetServiceAccountResponse;
    type DomainError = GetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ServiceAccountRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get(context, request)
    }
}

#[derive(Debug)]
pub struct ServiceAccountList;
impl RequestCapability for ServiceAccountList {
    type Request = ListServiceAccountsRequest;
    type Response = ListServiceAccountsResponse;
    type DomainError = ListError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ServiceAccountRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list(context, request)
    }
}

#[derive(Debug)]
pub struct ServiceAccountRevoke;
impl RequestCapability for ServiceAccountRevoke {
    type Request = RevokeServiceAccountRequest;
    type Response = RevokeServiceAccountResponse;
    type DomainError = RevokeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ServiceAccountRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke(context, request)
    }
}

#[derive(Debug)]
pub struct ServiceAccountRotateSecret;
impl RequestCapability for ServiceAccountRotateSecret {
    type Request = RotateServiceAccountSecretRequest;
    type Response = RotateServiceAccountSecretResponse;
    type DomainError = RotateSecretError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ROTATE_SECRET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ServiceAccountRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).rotate_secret(context, request)
    }
}

impl serde::Serialize for CreateError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessDenied => serializer.serialize_str("access_denied"),
            Self::DirectoryRejected => serializer.serialize_str("directory_rejected"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MembershipRequired => serializer.serialize_str("membership_required"),
            Self::NameConflict => serializer.serialize_str("name_conflict"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::TooManyServiceAccounts => serializer.serialize_str("too_many_service_accounts"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_denied" => Ok(Self::AccessDenied),
                "directory_rejected" => Ok(Self::DirectoryRejected),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "membership_required" => Ok(Self::MembershipRequired),
                "name_conflict" => Ok(Self::NameConflict),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "too_many_service_accounts" => Ok(Self::TooManyServiceAccounts),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessDenied => serializer.serialize_str("access_denied"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MembershipRequired => serializer.serialize_str("membership_required"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_denied" => Ok(Self::AccessDenied),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "membership_required" => Ok(Self::MembershipRequired),
                "not_found" => Ok(Self::NotFound),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessDenied => serializer.serialize_str("access_denied"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MembershipRequired => serializer.serialize_str("membership_required"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_denied" => Ok(Self::AccessDenied),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "membership_required" => Ok(Self::MembershipRequired),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessDenied => serializer.serialize_str("access_denied"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MembershipRequired => serializer.serialize_str("membership_required"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_denied" => Ok(Self::AccessDenied),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "membership_required" => Ok(Self::MembershipRequired),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RotateSecretError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AccessDenied => serializer.serialize_str("access_denied"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::MembershipRequired => serializer.serialize_str("membership_required"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Revoked => serializer.serialize_str("revoked"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RotateSecretError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "access_denied" => Ok(Self::AccessDenied),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "membership_required" => Ok(Self::MembershipRequired),
                "not_found" => Ok(Self::NotFound),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "revoked" => Ok(Self::Revoked),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_create_request(value: &CreateServiceAccountRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_request(wire: &str) -> Result<CreateServiceAccountRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_response(value: &CreateServiceAccountResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_response(wire: &str) -> Result<CreateServiceAccountResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_error(value: &CreateError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_error(wire: &str) -> Result<CreateError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_request(value: &GetServiceAccountRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request(wire: &str) -> Result<GetServiceAccountRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_response(value: &GetServiceAccountResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_response(wire: &str) -> Result<GetServiceAccountResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_error(value: &GetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_error(wire: &str) -> Result<GetError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_request(value: &ListServiceAccountsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_request(wire: &str) -> Result<ListServiceAccountsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_response(value: &ListServiceAccountsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_response(wire: &str) -> Result<ListServiceAccountsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_error(value: &ListError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_error(wire: &str) -> Result<ListError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_request(value: &RevokeServiceAccountRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_request(wire: &str) -> Result<RevokeServiceAccountRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_response(value: &RevokeServiceAccountResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_response(wire: &str) -> Result<RevokeServiceAccountResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_error(value: &RevokeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_error(wire: &str) -> Result<RevokeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_rotate_secret_request(value: &RotateServiceAccountSecretRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_rotate_secret_request(wire: &str) -> Result<RotateServiceAccountSecretRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_rotate_secret_response(value: &RotateServiceAccountSecretResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_rotate_secret_response(wire: &str) -> Result<RotateServiceAccountSecretResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_rotate_secret_error(value: &RotateSecretError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_rotate_secret_error(wire: &str) -> Result<RotateSecretError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoServiceAccountCreateResult {
    fn __lenso_into_result(self) -> Result<Result<CreateServiceAccountResponse, CreateError>, RuntimeFailure>;
}
impl __LensoIntoServiceAccountCreateResult for Result<CreateServiceAccountResponse, CreateError> {
    fn __lenso_into_result(self) -> Result<Result<CreateServiceAccountResponse, CreateError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoServiceAccountCreateResult for Result<Result<CreateServiceAccountResponse, CreateError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateServiceAccountResponse, CreateError>, RuntimeFailure> { self }
}
impl __LensoIntoServiceAccountCreateResult for Result<CreateServiceAccountResponse, lenso_plugin_authoring::PluginError<CreateError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateServiceAccountResponse, CreateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoServiceAccountCreateResult for Result<CreateServiceAccountResponse, ServiceAccountCreateInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateServiceAccountResponse, CreateError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ServiceAccountCreateInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ServiceAccountCreateInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoServiceAccountGetResult {
    fn __lenso_into_result(self) -> Result<Result<GetServiceAccountResponse, GetError>, RuntimeFailure>;
}
impl __LensoIntoServiceAccountGetResult for Result<GetServiceAccountResponse, GetError> {
    fn __lenso_into_result(self) -> Result<Result<GetServiceAccountResponse, GetError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoServiceAccountGetResult for Result<Result<GetServiceAccountResponse, GetError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetServiceAccountResponse, GetError>, RuntimeFailure> { self }
}
impl __LensoIntoServiceAccountGetResult for Result<GetServiceAccountResponse, lenso_plugin_authoring::PluginError<GetError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetServiceAccountResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoServiceAccountGetResult for Result<GetServiceAccountResponse, ServiceAccountGetInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetServiceAccountResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ServiceAccountGetInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ServiceAccountGetInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoServiceAccountListResult {
    fn __lenso_into_result(self) -> Result<Result<ListServiceAccountsResponse, ListError>, RuntimeFailure>;
}
impl __LensoIntoServiceAccountListResult for Result<ListServiceAccountsResponse, ListError> {
    fn __lenso_into_result(self) -> Result<Result<ListServiceAccountsResponse, ListError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoServiceAccountListResult for Result<Result<ListServiceAccountsResponse, ListError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListServiceAccountsResponse, ListError>, RuntimeFailure> { self }
}
impl __LensoIntoServiceAccountListResult for Result<ListServiceAccountsResponse, lenso_plugin_authoring::PluginError<ListError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListServiceAccountsResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoServiceAccountListResult for Result<ListServiceAccountsResponse, ServiceAccountListInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListServiceAccountsResponse, ListError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ServiceAccountListInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ServiceAccountListInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoServiceAccountRevokeResult {
    fn __lenso_into_result(self) -> Result<Result<RevokeServiceAccountResponse, RevokeError>, RuntimeFailure>;
}
impl __LensoIntoServiceAccountRevokeResult for Result<RevokeServiceAccountResponse, RevokeError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeServiceAccountResponse, RevokeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoServiceAccountRevokeResult for Result<Result<RevokeServiceAccountResponse, RevokeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RevokeServiceAccountResponse, RevokeError>, RuntimeFailure> { self }
}
impl __LensoIntoServiceAccountRevokeResult for Result<RevokeServiceAccountResponse, lenso_plugin_authoring::PluginError<RevokeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokeServiceAccountResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoServiceAccountRevokeResult for Result<RevokeServiceAccountResponse, ServiceAccountRevokeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeServiceAccountResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ServiceAccountRevokeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ServiceAccountRevokeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoServiceAccountRotateSecretResult {
    fn __lenso_into_result(self) -> Result<Result<RotateServiceAccountSecretResponse, RotateSecretError>, RuntimeFailure>;
}
impl __LensoIntoServiceAccountRotateSecretResult for Result<RotateServiceAccountSecretResponse, RotateSecretError> {
    fn __lenso_into_result(self) -> Result<Result<RotateServiceAccountSecretResponse, RotateSecretError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoServiceAccountRotateSecretResult for Result<Result<RotateServiceAccountSecretResponse, RotateSecretError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RotateServiceAccountSecretResponse, RotateSecretError>, RuntimeFailure> { self }
}
impl __LensoIntoServiceAccountRotateSecretResult for Result<RotateServiceAccountSecretResponse, lenso_plugin_authoring::PluginError<RotateSecretError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RotateServiceAccountSecretResponse, RotateSecretError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoServiceAccountRotateSecretResult for Result<RotateServiceAccountSecretResponse, ServiceAccountRotateSecretInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RotateServiceAccountSecretResponse, RotateSecretError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ServiceAccountRotateSecretInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ServiceAccountRotateSecretInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ServiceAccountProvider: fmt::Debug + 'static {
    fn create(&self, context: InvocationContext, request: CreateServiceAccountRequest) -> NativeRequestFuture<ServiceAccountCreate>;
    fn get(&self, context: InvocationContext, request: GetServiceAccountRequest) -> NativeRequestFuture<ServiceAccountGet>;
    fn list(&self, context: InvocationContext, request: ListServiceAccountsRequest) -> NativeRequestFuture<ServiceAccountList>;
    fn revoke(&self, context: InvocationContext, request: RevokeServiceAccountRequest) -> NativeRequestFuture<ServiceAccountRevoke>;
    fn rotate_secret(&self, context: InvocationContext, request: RotateServiceAccountSecretRequest) -> NativeRequestFuture<ServiceAccountRotateSecret>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_service_account {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportServiceAccount;
        impl $crate::ServiceAccountProvider for $plugin {
        fn create(&self, context: __LensoNativeSupportServiceAccount::InvocationContext, request: $crate::CreateServiceAccountRequest) -> __LensoNativeSupportServiceAccount::NativeRequestFuture<$crate::ServiceAccountCreate> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create(&plugin, context, request).await;
                $crate::__LensoIntoServiceAccountCreateResult::__lenso_into_result(result)
            })
        }
        fn get(&self, context: __LensoNativeSupportServiceAccount::InvocationContext, request: $crate::GetServiceAccountRequest) -> __LensoNativeSupportServiceAccount::NativeRequestFuture<$crate::ServiceAccountGet> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get(&plugin, context, request).await;
                $crate::__LensoIntoServiceAccountGetResult::__lenso_into_result(result)
            })
        }
        fn list(&self, context: __LensoNativeSupportServiceAccount::InvocationContext, request: $crate::ListServiceAccountsRequest) -> __LensoNativeSupportServiceAccount::NativeRequestFuture<$crate::ServiceAccountList> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list(&plugin, context, request).await;
                $crate::__LensoIntoServiceAccountListResult::__lenso_into_result(result)
            })
        }
        fn revoke(&self, context: __LensoNativeSupportServiceAccount::InvocationContext, request: $crate::RevokeServiceAccountRequest) -> __LensoNativeSupportServiceAccount::NativeRequestFuture<$crate::ServiceAccountRevoke> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke(&plugin, context, request).await;
                $crate::__LensoIntoServiceAccountRevokeResult::__lenso_into_result(result)
            })
        }
        fn rotate_secret(&self, context: __LensoNativeSupportServiceAccount::InvocationContext, request: $crate::RotateServiceAccountSecretRequest) -> __LensoNativeSupportServiceAccount::NativeRequestFuture<$crate::ServiceAccountRotateSecret> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::rotate_secret(&plugin, context, request).await;
                $crate::__LensoIntoServiceAccountRotateSecretResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct ServiceAccountRequestEndpoint { provider: Rc<dyn ServiceAccountProvider> }

#[derive(Debug)]
pub struct ServiceAccountEndpoint<P: ServiceAccountProvider> { provider: Rc<P>, request_endpoint: ServiceAccountRequestEndpoint }
impl<P: ServiceAccountProvider> ServiceAccountEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ServiceAccountProvider> = provider.clone();
        Self { provider, request_endpoint: ServiceAccountRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ServiceAccountProvider> NativeRequestEndpoint for ServiceAccountEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CREATE_OPERATION,
        GET_OPERATION,
        LIST_OPERATION,
        REVOKE_OPERATION,
        ROTATE_SECRET_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CREATE_OPERATION => {
                let Ok(request) = request.downcast::<CreateServiceAccountRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_OPERATION => {
                let Ok(request) = request.downcast::<GetServiceAccountRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_OPERATION => {
                let Ok(request) = request.downcast::<ListServiceAccountsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_OPERATION => {
                let Ok(request) = request.downcast::<RevokeServiceAccountRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            ROTATE_SECRET_OPERATION => {
                let Ok(request) = request.downcast::<RotateServiceAccountSecretRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).rotate_secret(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_service_account {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ServiceAccountEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_service_account {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_service_account!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ServiceAccountClient {
    create: NativeRequestHandle<ServiceAccountCreate>,
    get: NativeRequestHandle<ServiceAccountGet>,
    list: NativeRequestHandle<ServiceAccountList>,
    revoke: NativeRequestHandle<ServiceAccountRevoke>,
    rotate_secret: NativeRequestHandle<ServiceAccountRotateSecret>,
}
impl ServiceAccountClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn create(&self, request: CreateServiceAccountRequest) -> Result<CreateServiceAccountResponse, ServiceAccountCreateInvocationError> {
        self.create.invoke(CREATE_OPERATION, request).await
            .map_err(ServiceAccountCreateInvocationError::Runtime)?
            .map_err(ServiceAccountCreateInvocationError::Domain)
    }

    pub async fn create_with_context(&self, context: InvocationContext, request: CreateServiceAccountRequest) -> Result<CreateServiceAccountResponse, ServiceAccountCreateInvocationError> {
        self.create.invoke_with_context(CREATE_OPERATION, context, request).await
            .map_err(ServiceAccountCreateInvocationError::Runtime)?
            .map_err(ServiceAccountCreateInvocationError::Domain)
    }

    pub async fn get(&self, request: GetServiceAccountRequest) -> Result<GetServiceAccountResponse, ServiceAccountGetInvocationError> {
        self.get.invoke(GET_OPERATION, request).await
            .map_err(ServiceAccountGetInvocationError::Runtime)?
            .map_err(ServiceAccountGetInvocationError::Domain)
    }

    pub async fn get_with_context(&self, context: InvocationContext, request: GetServiceAccountRequest) -> Result<GetServiceAccountResponse, ServiceAccountGetInvocationError> {
        self.get.invoke_with_context(GET_OPERATION, context, request).await
            .map_err(ServiceAccountGetInvocationError::Runtime)?
            .map_err(ServiceAccountGetInvocationError::Domain)
    }

    pub async fn list(&self, request: ListServiceAccountsRequest) -> Result<ListServiceAccountsResponse, ServiceAccountListInvocationError> {
        self.list.invoke(LIST_OPERATION, request).await
            .map_err(ServiceAccountListInvocationError::Runtime)?
            .map_err(ServiceAccountListInvocationError::Domain)
    }

    pub async fn list_with_context(&self, context: InvocationContext, request: ListServiceAccountsRequest) -> Result<ListServiceAccountsResponse, ServiceAccountListInvocationError> {
        self.list.invoke_with_context(LIST_OPERATION, context, request).await
            .map_err(ServiceAccountListInvocationError::Runtime)?
            .map_err(ServiceAccountListInvocationError::Domain)
    }

    pub async fn revoke(&self, request: RevokeServiceAccountRequest) -> Result<RevokeServiceAccountResponse, ServiceAccountRevokeInvocationError> {
        self.revoke.invoke(REVOKE_OPERATION, request).await
            .map_err(ServiceAccountRevokeInvocationError::Runtime)?
            .map_err(ServiceAccountRevokeInvocationError::Domain)
    }

    pub async fn revoke_with_context(&self, context: InvocationContext, request: RevokeServiceAccountRequest) -> Result<RevokeServiceAccountResponse, ServiceAccountRevokeInvocationError> {
        self.revoke.invoke_with_context(REVOKE_OPERATION, context, request).await
            .map_err(ServiceAccountRevokeInvocationError::Runtime)?
            .map_err(ServiceAccountRevokeInvocationError::Domain)
    }

    pub async fn rotate_secret(&self, request: RotateServiceAccountSecretRequest) -> Result<RotateServiceAccountSecretResponse, ServiceAccountRotateSecretInvocationError> {
        self.rotate_secret.invoke(ROTATE_SECRET_OPERATION, request).await
            .map_err(ServiceAccountRotateSecretInvocationError::Runtime)?
            .map_err(ServiceAccountRotateSecretInvocationError::Domain)
    }

    pub async fn rotate_secret_with_context(&self, context: InvocationContext, request: RotateServiceAccountSecretRequest) -> Result<RotateServiceAccountSecretResponse, ServiceAccountRotateSecretInvocationError> {
        self.rotate_secret.invoke_with_context(ROTATE_SECRET_OPERATION, context, request).await
            .map_err(ServiceAccountRotateSecretInvocationError::Runtime)?
            .map_err(ServiceAccountRotateSecretInvocationError::Domain)
    }
}

impl CapabilityClient for ServiceAccountClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            create: dependencies.one::<ServiceAccountCreate>()?,
            get: dependencies.one::<ServiceAccountGet>()?,
            list: dependencies.one::<ServiceAccountList>()?,
            revoke: dependencies.one::<ServiceAccountRevoke>()?,
            rotate_secret: dependencies.one::<ServiceAccountRotateSecret>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ServiceAccountClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    create: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ServiceAccountCreate>()?,
                    get: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ServiceAccountGet>()?,
                    list: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ServiceAccountList>()?,
                    revoke: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ServiceAccountRevoke>()?,
                    rotate_secret: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ServiceAccountRotateSecret>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ServiceAccountCreateInvocationError {
    Domain(CreateError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ServiceAccountGetInvocationError {
    Domain(GetError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ServiceAccountListInvocationError {
    Domain(ListError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ServiceAccountRevokeInvocationError {
    Domain(RevokeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ServiceAccountRotateSecretInvocationError {
    Domain(RotateSecretError),
    Runtime(RuntimeFailure),
}
