// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.auth.service-account@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SERVICE_ACCOUNT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SERVICE_ACCOUNT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_service_account { () => { "{\"capability_id\":\"lenso.auth.service-account@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"exchange_secret\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_service_account_client { () => { "{\"capability_id\":\"lenso.auth.service-account@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_service_account_client { () => { "{\"capability_id\":\"lenso.auth.service-account@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const EXCHANGE_SECRET_OPERATION: &str = "exchange_secret";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExchangeServiceAccountSecretRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "secret")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub secret: String,
}

impl fmt::Debug for ExchangeServiceAccountSecretRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ExchangeServiceAccountSecretRequest")
            .field("idempotency_key", &self.idempotency_key)
            .field("secret", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExchangeServiceAccountSecretResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "service_account_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_account_id: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for ExchangeServiceAccountSecretResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ExchangeServiceAccountSecretResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("organization_id", &self.organization_id)
            .field("service_account_id", &self.service_account_id)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExchangeSecretError {
    Disabled,
    Forbidden,
    IdempotencyConflict,
    InvalidCredentials,
    InvalidRequest,
    OperationInProgress,
    RateLimited,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ServiceAccount;
impl RequestCapability for ServiceAccount {
    type Request = ExchangeServiceAccountSecretRequest;
    type Response = ExchangeServiceAccountSecretResponse;
    type DomainError = ExchangeSecretError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXCHANGE_SECRET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ServiceAccountRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).exchange_secret(context, request)
    }
}

impl serde::Serialize for ExchangeSecretError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidCredentials => serializer.serialize_str("invalid_credentials"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RateLimited => serializer.serialize_str("rate_limited"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExchangeSecretError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_credentials" => Ok(Self::InvalidCredentials),
                "invalid_request" => Ok(Self::InvalidRequest),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "rate_limited" => Ok(Self::RateLimited),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_exchange_secret_request(value: &ExchangeServiceAccountSecretRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_secret_request(wire: &str) -> Result<ExchangeServiceAccountSecretRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_exchange_secret_response(value: &ExchangeServiceAccountSecretResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_secret_response(wire: &str) -> Result<ExchangeServiceAccountSecretResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_exchange_secret_error(value: &ExchangeSecretError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_exchange_secret_error(wire: &str) -> Result<ExchangeSecretError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoServiceAccountExchangeSecretResult {
    fn __lenso_into_result(self) -> Result<Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError>, RuntimeFailure>;
}
impl __LensoIntoServiceAccountExchangeSecretResult for Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoServiceAccountExchangeSecretResult for Result<Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError>, RuntimeFailure> { self }
}
impl __LensoIntoServiceAccountExchangeSecretResult for Result<ExchangeServiceAccountSecretResponse, lenso_plugin_authoring::PluginError<ExchangeSecretError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoServiceAccountExchangeSecretResult for Result<ExchangeServiceAccountSecretResponse, ServiceAccountInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExchangeServiceAccountSecretResponse, ExchangeSecretError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ServiceAccountInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ServiceAccountInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ServiceAccountProvider: fmt::Debug + 'static {
    fn exchange_secret(&self, context: InvocationContext, request: ExchangeServiceAccountSecretRequest) -> NativeRequestFuture<ServiceAccount>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_service_account {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportServiceAccount;
        impl $crate::ServiceAccountProvider for $plugin {
        fn exchange_secret(&self, context: __LensoNativeSupportServiceAccount::InvocationContext, request: $crate::ExchangeServiceAccountSecretRequest) -> __LensoNativeSupportServiceAccount::NativeRequestFuture<$crate::ServiceAccount> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::exchange_secret(&plugin, context, request).await;
                $crate::__LensoIntoServiceAccountExchangeSecretResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct ServiceAccountRequestEndpoint { provider: Rc<dyn ServiceAccountProvider> }

#[derive(Debug)]
pub struct ServiceAccountEndpoint<P: ServiceAccountProvider> { provider: Rc<P>, request_endpoint: ServiceAccountRequestEndpoint }
impl<P: ServiceAccountProvider> ServiceAccountEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ServiceAccountProvider> = provider.clone();
        Self { provider, request_endpoint: ServiceAccountRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ServiceAccountProvider> NativeRequestEndpoint for ServiceAccountEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        EXCHANGE_SECRET_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            EXCHANGE_SECRET_OPERATION => {
                let Ok(request) = request.downcast::<ExchangeServiceAccountSecretRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).exchange_secret(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_service_account {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ServiceAccountEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_service_account {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_service_account!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ServiceAccountClient {
    exchange_secret: NativeRequestHandle<ServiceAccount>,
}
impl ServiceAccountClient {
    pub fn new(handle: NativeRequestHandle<ServiceAccount>) -> Self {
        Self { exchange_secret: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn exchange_secret(&self, request: ExchangeServiceAccountSecretRequest) -> Result<ExchangeServiceAccountSecretResponse, ServiceAccountInvocationError> {
        self.exchange_secret.invoke(EXCHANGE_SECRET_OPERATION, request).await
            .map_err(ServiceAccountInvocationError::Runtime)?
            .map_err(ServiceAccountInvocationError::Domain)
    }

    pub async fn exchange_secret_with_context(&self, context: InvocationContext, request: ExchangeServiceAccountSecretRequest) -> Result<ExchangeServiceAccountSecretResponse, ServiceAccountInvocationError> {
        self.exchange_secret.invoke_with_context(EXCHANGE_SECRET_OPERATION, context, request).await
            .map_err(ServiceAccountInvocationError::Runtime)?
            .map_err(ServiceAccountInvocationError::Domain)
    }
}

impl CapabilityClient for ServiceAccountClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            exchange_secret: dependencies.one::<ServiceAccount>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ServiceAccountClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    exchange_secret: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ServiceAccount>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ServiceAccountInvocationError {
    Domain(ExchangeSecretError),
    Runtime(RuntimeFailure),
}
